import React from "react";
import type { ScoreBreakdownItem } from "../types";
import { SENSITIVE_PENALTIES, NONSENSITIVE_BONUSES } from "../utils/scoreCalculator";

interface ScoreBreakdownProps {
  breakdown: ScoreBreakdownItem[];
}

const formatImpact = (impact: number): string => {
  return impact > 0 ? `+${impact}` : `${impact}`;
};

export const ScoreBreakdown: React.FC<ScoreBreakdownProps> = ({ breakdown }) => {
  return (
    <details className="rounded-lg border border-slate-200 bg-white p-3 shadow-sm">
      <summary className="cursor-pointer list-none text-sm font-semibold text-slate-900">
        How was this score calculated?
      </summary>

      <div className="mt-3 overflow-x-auto">
        <table className="w-full border-collapse text-left text-xs">
          <thead>
            <tr className="border-b border-slate-200 text-slate-600">
              <th className="py-2 pr-2 font-semibold">Signal</th>
              <th className="py-2 pr-2 font-semibold">Impact</th>
              <th className="py-2 font-semibold">Reason</th>
            </tr>
          </thead>
          <tbody>
            {breakdown.length === 0 && (
              <tr>
                <td className="py-3 text-slate-600" colSpan={3}>
                  No score-impacting signals were found in the analysis output.
                </td>
              </tr>
            )}
            {breakdown.map((item) => (
              <tr key={`${item.label}-${item.reason}`} className="border-b border-slate-100 align-top">
                <td className="py-2 pr-2 text-slate-800">{item.label}</td>
                <td
                  className={`py-2 pr-2 font-semibold ${
                    item.impact >= 0 ? "text-green-700" : "text-red-700"
                  }`}
                >
                  {formatImpact(item.impact)}
                </td>
                <td className="py-2 text-slate-700">{item.reason}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-3 text-xs text-slate-600">
        This score is computed algorithmically from flagged practices. It is not generated by the AI.
      </p>

      <div className="mt-3 rounded-md border border-slate-200 bg-slate-50 p-3 text-xs">
        <p className="font-semibold text-slate-800">Scoring formula</p>
        <p className="mt-1 text-slate-600">
          Score&nbsp;=&nbsp;100&nbsp;&minus;&nbsp;penalties&nbsp;+&nbsp;bonuses (clamped to 0–100).
          Penalties are capped at&nbsp;−80 before bonuses are applied.
        </p>

        <div className="mt-3 grid grid-cols-2 gap-3">
          <div>
            <p className="mb-1 font-semibold text-red-700">Deductions</p>
            <table className="w-full border-collapse text-left">
              <tbody>
                {Object.entries(SENSITIVE_PENALTIES).map(([label, pts]) => (
                  <tr key={label} className="border-b border-slate-100">
                    <td className="py-1 pr-2 capitalize text-slate-700">{label}</td>
                    <td className="py-1 text-right font-semibold text-red-700">−{pts}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div>
            <p className="mb-1 font-semibold text-green-700">Bonuses</p>
            <table className="w-full border-collapse text-left">
              <tbody>
                {Object.entries(NONSENSITIVE_BONUSES).map(([label, pts]) => (
                  <tr key={label} className="border-b border-slate-100">
                    <td className="py-1 pr-2 capitalize text-slate-700">{label}</td>
                    <td className="py-1 text-right font-semibold text-green-700">+{pts}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </details>
  );
};
